
package lab.web.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileService", targetNamespace = "http://soap.web.lab/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "writeFile", targetNamespace = "http://soap.web.lab/", className = "lab.web.soap.WriteFile")
    @ResponseWrapper(localName = "writeFileResponse", targetNamespace = "http://soap.web.lab/", className = "lab.web.soap.WriteFileResponse")
    public boolean writeFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListAllFiles", targetNamespace = "http://soap.web.lab/", className = "lab.web.soap.GetListAllFiles")
    @ResponseWrapper(localName = "getListAllFilesResponse", targetNamespace = "http://soap.web.lab/", className = "lab.web.soap.GetListAllFilesResponse")
    public List<String> getListAllFiles();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteFile", targetNamespace = "http://soap.web.lab/", className = "lab.web.soap.DeleteFile")
    @ResponseWrapper(localName = "deleteFileResponse", targetNamespace = "http://soap.web.lab/", className = "lab.web.soap.DeleteFileResponse")
    public boolean deleteFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ServiceException
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadFile", targetNamespace = "http://soap.web.lab/", className = "lab.web.soap.DownloadFile")
    @ResponseWrapper(localName = "downloadFileResponse", targetNamespace = "http://soap.web.lab/", className = "lab.web.soap.DownloadFileResponse")
    public boolean downloadFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws ServiceException
    ;

}
