
package lab.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileServiceImplService", targetNamespace = "http://soap.web.lab/", wsdlLocation = "http://localhost:8080/MykhailoKozakFileStorageService/fileSOAP?wsdl")
public class FileServiceImplService
    extends Service
{

    private final static URL FILESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FILESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName FILESERVICEIMPLSERVICE_QNAME = new QName("http://soap.web.lab/", "FileServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/MykhailoKozakFileStorageService/fileSOAP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        FILESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public FileServiceImplService() {
        super(__getWsdlLocation(), FILESERVICEIMPLSERVICE_QNAME);
    }

    public FileServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILESERVICEIMPLSERVICE_QNAME, features);
    }

    public FileServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, FILESERVICEIMPLSERVICE_QNAME);
    }

    public FileServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILESERVICEIMPLSERVICE_QNAME, features);
    }

    public FileServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FileService
     */
    @WebEndpoint(name = "FileServiceImplPort")
    public FileService getFileServiceImplPort() {
        return super.getPort(new QName("http://soap.web.lab/", "FileServiceImplPort"), FileService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileService
     */
    @WebEndpoint(name = "FileServiceImplPort")
    public FileService getFileServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.web.lab/", "FileServiceImplPort"), FileService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw FILESERVICEIMPLSERVICE_EXCEPTION;
        }
        return FILESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
